name: CI0

on:
  push:
  pull_request:

jobs:

  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id
    strategy:
      matrix:
        tmp: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
      fail-fast: false
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.404
                  
      # Workaround for https://github.com/actions/setup-dotnet/issues/155
      # - name: nuget list source
      #  run: dotnet nuget list source
        
      # Workaround for https://github.com/actions/setup-dotnet/issues/155
      # - name: Clear http-cache
      #  run: dotnet nuget locals http-cache --clear
        
      # Workaround for https://github.com/actions/setup-dotnet/issues/155
      # - name: locals all -l
      #  run: dotnet nuget locals all -l

      - name: Restore
        run: dotnet restore -p:TreatWarningsAsErrors=true --disable-parallel 
