name: CI

on:
  push:
  pull_request:

jobs:

  
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id
    strategy:
      matrix:
        tmp: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
      fail-fast: false
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.404
           
      - name: Dir Temp
        run: dir C:\Users\runneradmin\AppData\Local\Temp
              
      - name: Dir AppData
        run: dir C:\Users\runneradmin\AppData\Local\
        
      - name: Dir runneradmin
        run: dir C:\Users\runneradmin
        
      # Workaround for https://github.com/NuGet/Home/issues/10586
      # - name: nuget list source
      #  run: dotnet nuget list source

      #################################################################
      # Registered Sources:
      # 1.  nuget.org [Enabled]
      # https://api.nuget.org/v3/index.json
      # 2.  Microsoft Visual Studio Offline Packages [Enabled]
      # C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
      #################################################################
      
      # Workaround for https://github.com/NuGet/Home/issues/10586
      # - name: Clear http-cache
      #  run: dotnet nuget locals http-cache --clear
        
      # Workaround for https://github.com/NuGet/Home/issues/10586
      # - name: locals all -l
      #  run: dotnet nuget locals all -l
        
      #################################################################
      # http-cache: C:\Users\runneradmin\AppData\Local\NuGet\v3-cache
      # global-packages: C:\Users\runneradmin\.nuget\packages\
      # temp: C:\Users\runneradmin\AppData\Local\Temp\NuGetScratch
      # plugins-cache: C:\Users\runneradmin\AppData\Local\NuGet\plugins-cache
      #################################################################

      - name: Restore
        # `-v:diag` reduces chances of getting restore errors ?!
        # run: dotnet restore -p:TreatWarningsAsErrors=true --disable-parallel -v:diag
        run: dotnet restore -p:TreatWarningsAsErrors=true --disable-parallel 
